#!/usr/bin/env bash
# Downloads pinned third-party assets into vendor/. Requires only curl and tar.
# Re-run after changing a version below; commit the resulting vendor/ tree.
set -euo pipefail

MARKDOWN_IT=14.3.2
HIGHLIGHT=11.12.0
# Appended to the common-languages bundle (technical work beyond the defaults).
HIGHLIGHT_EXTRA="latex matlab julia verilog vhdl fortran dockerfile"
KATEX=0.18.9
FONTSOURCE=5.3.0

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VENDOR="$ROOT/vendor"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# fetch_pkg <npm-name> <version> → extracts to $TMP/<safe-name>/package
fetch_pkg() {
  local name="$1" version="$2" base="${1##*/}"
  local dir="$TMP/${name//\//_}"
  mkdir -p "$dir"
  curl -fsSL "https://registry.npmjs.org/$name/-/$base-$version.tgz" | tar xz -C "$dir"
  echo "$dir/package"
}

rm -rf "$VENDOR"
mkdir -p "$VENDOR"/{markdown-it,highlight,katex/fonts,fonts}

pkg=$(fetch_pkg markdown-it "$MARKDOWN_IT")
cp "$pkg/dist/markdown-it.min.js" "$pkg/LICENSE" "$VENDOR/markdown-it/"

pkg=$(fetch_pkg @highlightjs/cdn-assets "$HIGHLIGHT")
cp "$pkg/LICENSE" "$VENDOR/highlight/"
{
  cat "$pkg/highlight.min.js"
  for lang in $HIGHLIGHT_EXTRA; do echo; cat "$pkg/languages/$lang.min.js"; done
} > "$VENDOR/highlight/highlight.min.js"

pkg=$(fetch_pkg katex "$KATEX")
cp "$pkg/dist/katex.min.js" "$pkg/dist/katex.min.css" "$pkg/LICENSE" "$VENDOR/katex/"
# mhchem: \ce{…} chemical equations and \pu{…} units (registers on the global katex).
cp "$pkg/dist/contrib/mhchem.min.js" "$VENDOR/katex/"
cp "$pkg"/dist/fonts/*.woff2 "$VENDOR/katex/fonts/"

pkg=$(fetch_pkg @fontsource-variable/inter "$FONTSOURCE")
cp "$pkg/files/inter-latin-wght-normal.woff2" "$pkg/files/inter-latin-wght-italic.woff2" "$VENDOR/fonts/"
cp "$pkg/LICENSE" "$VENDOR/fonts/LICENSE-inter.txt"

pkg=$(fetch_pkg @fontsource-variable/jetbrains-mono "$FONTSOURCE")
cp "$pkg/files/jetbrains-mono-latin-wght-normal.woff2" "$VENDOR/fonts/"
cp "$pkg/LICENSE" "$VENDOR/fonts/LICENSE-jetbrains-mono.txt"

pkg=$(fetch_pkg @fontsource/zen-maru-gothic "$FONTSOURCE")
cp "$pkg/files/zen-maru-gothic-latin-500-normal.woff2" "$pkg/files/zen-maru-gothic-latin-700-normal.woff2" "$VENDOR/fonts/"
cp "$pkg/LICENSE" "$VENDOR/fonts/LICENSE-zen-maru-gothic.txt"

# Lets Node tests require() the UMD builds despite the root "type": "module".
echo '{ "type": "commonjs" }' > "$VENDOR/package.json"

cat > "$VENDOR/VERSIONS.md" <<EOF
# Vendored dependencies

Generated by \`scripts/vendor.sh\`. Do not edit files in \`vendor/\` by hand.

| Package | Version | Files |
|---|---|---|
| markdown-it | $MARKDOWN_IT | \`markdown-it/markdown-it.min.js\` (global \`markdownit\`) |
| @highlightjs/cdn-assets | $HIGHLIGHT | \`highlight/highlight.min.js\` (global \`hljs\`, common languages + $HIGHLIGHT_EXTRA) |
| katex | $KATEX | \`katex/katex.min.js\` (global \`katex\`), \`katex.min.css\`, woff2 fonts, \`katex/mhchem.min.js\` (chemistry extension: \`\\ce{}\`, \`\\pu{}\`) |
| @fontsource-variable/inter | $FONTSOURCE | \`fonts/inter-latin-wght-*.woff2\` (OFL) |
| @fontsource-variable/jetbrains-mono | $FONTSOURCE | \`fonts/jetbrains-mono-latin-wght-normal.woff2\` (OFL) |
| @fontsource/zen-maru-gothic | $FONTSOURCE | \`fonts/zen-maru-gothic-latin-{500,700}-normal.woff2\` (OFL) |
EOF

echo "Vendored into $VENDOR"
